import {
  Files,
  Scissors,
  Trash2,
  FileOutput,
  ListOrdered,
  RotateCw,
  Crop,
  Image as ImageIcon,
  FileImage,
  Stamp,
  Hash,
  Lock,
  Unlock,
  FileDown,
  Eye,
  Download,
} from 'lucide-react';

export interface ToolMeta {
  id: string;
  num: string;
  title: string;
  description: string;
  icon: any;
  badgeColor: string;
  textColor: string;
  iconBg: string;
}

export const PDF_TOOLS: ToolMeta[] = [
  {
    id: 'merge-pdf',
    num: '01',
    title: 'Merge PDFs',
    description: 'Combine multiple PDF files into a single PDF.',
    icon: Files,
    badgeColor: 'bg-blue-50 text-blue-600 border-blue-200',
    textColor: 'text-blue-600',
    iconBg: 'bg-blue-100 text-blue-600',
  },
  {
    id: 'split-pdf',
    num: '02',
    title: 'Split PDFs',
    description: 'Split a PDF into multiple separate PDF files.',
    icon: Scissors,
    badgeColor: 'bg-emerald-50 text-emerald-600 border-emerald-200',
    textColor: 'text-emerald-600',
    iconBg: 'bg-emerald-100 text-emerald-600',
  },
  {
    id: 'remove-pages',
    num: '03',
    title: 'Remove Pages',
    description: 'Remove unwanted pages from your PDF.',
    icon: Trash2,
    badgeColor: 'bg-rose-50 text-rose-600 border-rose-200',
    textColor: 'text-rose-600',
    iconBg: 'bg-rose-100 text-rose-600',
  },
  {
    id: 'extract-pages',
    num: '04',
    title: 'Extract Pages',
    description: 'Extract specific pages and save as a new PDF.',
    icon: FileOutput,
    badgeColor: 'bg-purple-50 text-purple-600 border-purple-200',
    textColor: 'text-purple-600',
    iconBg: 'bg-purple-100 text-purple-600',
  },
  {
    id: 'reorder-pages',
    num: '05',
    title: 'Reorder Pages',
    description: 'Rearrange pages in any order you want.',
    icon: ListOrdered,
    badgeColor: 'bg-teal-50 text-teal-600 border-teal-200',
    textColor: 'text-teal-600',
    iconBg: 'bg-teal-100 text-teal-600',
  },
  {
    id: 'rotate-pdf',
    num: '06',
    title: 'Rotate Pages',
    description: 'Rotate PDF pages to the desired orientation.',
    icon: RotateCw,
    badgeColor: 'bg-pink-50 text-pink-600 border-pink-200',
    textColor: 'text-pink-600',
    iconBg: 'bg-pink-100 text-pink-600',
  },
  {
    id: 'crop-pdf',
    num: '07',
    title: 'Crop PDF',
    description: 'Crop pages to remove margins or unwanted areas.',
    icon: Crop,
    badgeColor: 'bg-indigo-50 text-indigo-600 border-indigo-200',
    textColor: 'text-indigo-600',
    iconBg: 'bg-indigo-100 text-indigo-600',
  },
  {
    id: 'pdf-to-images',
    num: '08',
    title: 'PDF to Images',
    description: 'Convert PDF pages to images (PNG/JPG).',
    icon: ImageIcon,
    badgeColor: 'bg-green-50 text-green-600 border-green-200',
    textColor: 'text-green-600',
    iconBg: 'bg-green-100 text-green-600',
  },
  {
    id: 'images-to-pdf',
    num: '09',
    title: 'Images to PDF',
    description: 'Convert images (PNG/JPG) into a single PDF.',
    icon: FileImage,
    badgeColor: 'bg-amber-50 text-amber-600 border-amber-200',
    textColor: 'text-amber-600',
    iconBg: 'bg-amber-100 text-amber-600',
  },
  {
    id: 'add-watermark',
    num: '10',
    title: 'Add Watermark',
    description: 'Add text or image watermark to your PDF.',
    icon: Stamp,
    badgeColor: 'bg-violet-50 text-violet-600 border-violet-200',
    textColor: 'text-violet-600',
    iconBg: 'bg-violet-100 text-violet-600',
  },
  {
    id: 'add-page-numbers',
    num: '11',
    title: 'Add Page Numbers',
    description: 'Add page numbers to your PDF pages.',
    icon: Hash,
    badgeColor: 'bg-sky-50 text-sky-600 border-sky-200',
    textColor: 'text-sky-600',
    iconBg: 'bg-sky-100 text-sky-600',
  },
  {
    id: 'protect-pdf',
    num: '12',
    title: 'Password Protect',
    description: 'Protect your PDF with a password.',
    icon: Lock,
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    textColor: 'text-emerald-700',
    iconBg: 'bg-emerald-100 text-emerald-700',
  },
  {
    id: 'unlock-pdf',
    num: '13',
    title: 'Unlock PDF',
    description: 'Remove password protection (if password is known).',
    icon: Unlock,
    badgeColor: 'bg-red-50 text-red-600 border-red-200',
    textColor: 'text-red-600',
    iconBg: 'bg-red-100 text-red-600',
  },
  {
    id: 'compress-pdf',
    num: '14',
    title: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality.',
    icon: FileDown,
    badgeColor: 'bg-cyan-50 text-cyan-600 border-cyan-200',
    textColor: 'text-cyan-600',
    iconBg: 'bg-cyan-100 text-cyan-600',
  },
  {
    id: 'view-pdf',
    num: '15',
    title: 'View PDF',
    description: 'View PDF files directly in the browser.',
    icon: Eye,
    badgeColor: 'bg-fuchsia-50 text-fuchsia-600 border-fuchsia-200',
    textColor: 'text-fuchsia-600',
    iconBg: 'bg-fuchsia-100 text-fuchsia-600',
  },
  {
    id: 'download-share',
    num: '16',
    title: 'Download PDF',
    description: 'Download processed PDF or ZIP files to your device.',
    icon: Download,
    badgeColor: 'bg-orange-50 text-orange-600 border-orange-200',
    textColor: 'text-orange-600',
    iconBg: 'bg-orange-100 text-orange-600',
  },
];
